version: "3.1"

services:
  main:
    image: mysql:8
    container_name: live.mysql
    labels:
      svc: live.mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - live_backend
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "ITpg`01M[ls94l7xWD?n94hb0SL|r)"
    command: ["--default-time-zone=UTC"]

networks:
  live_backend:
    name: live_backend
    driver: bridge

volumes:
  data-volume:
